fail npm install
```
====>> npm install
  #!/bin/bash -eo pipefail
npm install
npm WARN package.json core-js@1.2.7 No README data
npm WARN package.json jsesc@1.3.0 No README data
npm WARN package.json obuf@1.1.1 No description
npm WARN package.json obuf@1.1.1 No README data
npm WARN package.json setimmediate@1.0.5 No README data
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json indexof@0.0.1 No repository field.
npm WARN package.json postcss-custom-media@5.0.1 scripts['tests'] should probably be scripts['test'].
npm WARN package.json require-from-string@1.2.1 keywords should be an array of strings
npm WARN prefer global coffee-script@1.12.5 should be installed with -g

> fsevents@1.1.1 install /home/ubuntu/cci-demo-rails/node_modules/fsevents
> node install

sh: 1: node: not found

npm ERR! fsevents@1.1.1 install: `node install`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the fsevents@1.1.1 install script.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.27-moby
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ubuntu/cci-demo-rails
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/cci-demo-rails/npm-debug.log
npm ERR! not ok code 0
Error: Exited with code 1
Step failed
Task failed
```